# Generated by Django 4.2.14 on 2024-08-28 06:08

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0014_add_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="odt_template",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=book.models.export_template_filename,
            ),
        ),
    ]
