# Generated by Django 4.2.14 on 2024-09-13 11:28

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0015_book_odt_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="docx_template",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=book.models.export_template_filename,
            ),
        ),
    ]
