name: CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Python dependencies
        run: |
          pip install wheel
          pip install pip --upgrade
          if grep version setup.py | grep -q "dev";
            then pip install https://github.com/fiduswriter/fiduswriter/archive/develop.zip;
            else pip install https://github.com/fiduswriter/fiduswriter/archive/master.zip;
          fi
          cd fiduswriter
          mv ../ci/configuration.py ./
          mv ../ci/.coveragerc ./
          pip install requests[security]
          pip install coverage
          pip install coveralls
          pip install selenium
          pip install flake8
          coverage run $(which fiduswriter) setup --no-static
      - name: Run linters
        run: |
          cd fiduswriter
          fiduswriter lint
      - name: Run tests
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 8
          max_attempts: 3
          retry_on: error
          command: |
            cd fiduswriter
            coverage run --concurrency=multiprocessing $(which fiduswriter) test book
      - name: Coveralls
        run: |
            cd fiduswriter
            coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
